### ISSUE TITLE
请问AG145夹爪对应的<arg name="GripperModel" default=""/>应该是什么？

### ISSUE THREAD

**Issue by Necolizer** [DH-Robotics/ros-gripper#6]
您好，在[dh_gripper.launch](https://github.com/DH-Robotics/dh_gripper_ros/blob/master/dh_gripper_driver/launch/dh_gripper.launch)中没有指明AG145的GripperModel参数应该如何设置。希望能得到帮助。非常感谢！

**Comment by Justin-Riekehof** [comment]
@Necolizer after cloning the rep and trying to build with 'catkin make' I get the following error:
**fatal error: dh_gripper_msgs/GripperCtrl.h: No such file or directory**
The .h of the gripper messages are not part of the rep... How did you get it running? Do I need to install some ros package?

Thank you for your support :)

Kind regards,
Justin

**Comment by Necolizer** [comment]
Hi @Justin-Riekehof . I'm not the rep holder but just a user. I have not encountered this error in my building process.
Maybe you can refer to [this link](https://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv). It says "Any .msg file in the msg directory will generate code for use in all supported languages. The C++ message header file will be generated in ~/catkin_ws/devel/include/beginner_tutorials/. " 
So the .h of the gripper messages (.msg) should be generated after your compilation, right? The problem might be related to `CMakeFile.txt`, `CMakeCache.txt` or the path to `~/catkin_ws/devel`, I guess. See [this question](https://answers.ros.org/question/9468/nav_msgsodometryh-no-such-file-or-directory/).

**Comment by Keithllin** [comment]
@Necolizer似乎ag系列的两个二指夹爪的grippermodel参数都是共用ag95 modbus的，我使用默认参数成功初始化了145夹爪

**Comment by Necolizer** [comment]
@Keithllin 对的，我在那之后发现似乎设置成`AG95_MB`，`PGE`之类的都行。[test脚本](https://github.com/DH-Robotics/dh_gripper_ros/blob/master/dh_gripper_driver/src/dh_gripper_Test.cpp)只要能进ModbusGripper_test()这个函数就可以了。并且只要不是`RGI`和`DH3_CAN`，[这个文件](https://github.com/DH-Robotics/dh_gripper_ros/blob/master/dh_gripper_driver/src/dh_gripper_driver.cpp)的line 38-48都不会进入。
